name: Build SDK
on:
  workflow_call:
    inputs:
      version:
        description: 'generated sdk version'
        required: true
        type: string
      name:
        description: 'generated sdk name'
        required: true
        type: string
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
        type: string
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: Build_with_Maven
        run: mvn clean install
      - name: Generate_SDK_Files
        working-directory: openapi
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=${{ inputs.fileAsBase64 }}"
      - uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: ./openapi/target/sdk
  copy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: copy
        run: |
          cp -a ./openapi/target/sdk/. ./generated/
  publish:
    runs-on: ubuntu-latest
    needs: copy
    steps:
      - name: create pull request
        run: gh pr create -B main -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}